[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "wiedan"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["PyYAML", "PySide6"]

[project.scripts]
wiedan = "wiedan.apps.main_window:main"

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
wiedan = ["data/**/*.yaml", "ui/svg/*.svg"]
